import type { ThemeAssets } from "./interfaces";

export const theme: ThemeAssets = {
    "code-vibes-theme": [
        "assets/img/themes/code/Property 1=Component 22-1.png",
        "assets/img/themes/code/Property 1=Component 22-2.png",
        "assets/img/themes/code/Property 1=Component 22-3.png",
        "assets/img/themes/code/Property 1=Component 22-4.png",
        "assets/img/themes/code/Property 1=Component 22-5.png",
        "assets/img/themes/code/Property 1=Component 22-6.png",
        "assets/img/themes/code/Property 1=Component 22-7.png",
        "assets/img/themes/code/Property 1=Component 22-8.png",
        "assets/img/themes/code/Property 1=Component 22-9.png",
        "assets/img/themes/code/Property 1=Component 22-10.png",
        "assets/img/themes/code/Property 1=Component 22-11.png",
        "assets/img/themes/code/Property 1=Component 22-12.png",
        "assets/img/themes/code/Property 1=Component 22-13.png",
        "assets/img/themes/code/Property 1=Component 22-14.png",
        "assets/img/themes/code/Property 1=Component 22-15.png",
        "assets/img/themes/code/Property 1=Component 22-16.png",
        "assets/img/themes/code/Property 1=Component 22-17.png",
        "assets/img/themes/code/Property 1=Component 22-18.png",
    ],
    codeFront: ["assets/img/themes/code/Front.png"],
    "gaming-theme": [
        "assets/img/themes/gaming/Asset3@2x1.png",
        "assets/img/themes/gaming/Asset4@2x1.png",
        "assets/img/themes/gaming/Asset5@2x1.png",
        "assets/img/themes/gaming/Asset6@2x1.png",
        "assets/img/themes/gaming/Asset7@2x1.png",
        "assets/img/themes/gaming/Asset8@2x1.png",
        "assets/img/themes/gaming/Asset9@2x1.png",
        "assets/img/themes/gaming/Asset10@2x1.png",
        "assets/img/themes/gaming/Asset11@2x1.png",
        "assets/img/themes/gaming/Asset12@2x1.png",
        "assets/img/themes/gaming/Asset13@2x1.png",
        "assets/img/themes/gaming/Asset14@2x1.png",
        "assets/img/themes/gaming/Asset15@2x1.png",
        "assets/img/themes/gaming/Asset16@2x1.png",
        "assets/img/themes/gaming/Asset17@2x1.png",
        "assets/img/themes/gaming/Asset18@2x1.png",
        "assets/img/themes/gaming/Asset2@2x1.png",
        "assets/img/themes/gaming/Asset1@2x1.png",
    ],
    gamingFront: ["assets/img/themes/gaming/Front.png"]
};
